apiVersion: apps/v1
kind: Deployment
metadata:
  name: klustered
spec:
  selector:
    matchLabels:
      app: klustered
  template:
    metadata:
      labels:
        app: klustered
    spec:
      containers:
        - name: klustered
          image: ghcr.io/rawkodeacademy/klustered:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
