apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-kluster-014-control-plane-wprkz
  namespace: kube-system
spec:
  containers:
  - image: nginx
    name: kube-scheduler-kluster-014-control-plane-wprkz
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: kluster-014-control-plane-wprkz
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
status: {}
