apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: honk
spec:
  acme:
    email: <redacted>
    privateKeySecretRef:
      name: mattermost-acme
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
